name: Build Millennium

on:
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true  # allow fortnite wallhacks 
      

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install MSVC
      uses: microsoft/setup-msbuild@v1.0.0

    - name: Restore NuGet packages
      working-directory: ./vendor/millennium
      run: nuget restore

    - name: Build project
      working-directory: ./vendor/millennium
      run: |
        msbuild millennium.sln /p:Configuration=Release /p:Platform=x86

  checksum:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Calculate Artifact Hash
      id: calculate-hash
      run: |
        echo "::set-output name=hash::$(sha256sum millennium.installer/build/output/Millennium.Installer-Windows.exe | cut -d ' ' -f 1)"
              
    - name: Create Checksum File
      run: |
        echo "${{ steps.calculate-hash.outputs.hash }}" > checksum.sha256
      working-directory: millennium.installer/build/output/

    - name: Set MSBuild path
      run: |
        echo "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin" >> $GITHUB_PATH 
      shell: cmd

